export const AUDIO_MAP = {
  "Ain’t": require("./assets/audio/ain't.mp3"),
  "Y’all": require("./assets/audio/Y'all.mp3"),
  "Folks": require("./assets/audio/folks.mp3"),
  "Howdy": require("./assets/audio/Howdy.mp3"),
  "Partner": require("./assets/audio/Partner.mp3"),
  "Giddy up": require("./assets/audio/Giddy up.mp3"),
  "Whoa": require("./assets/audio/Whoa.mp3"),
  "Reckon": require("./assets/audio/Reckon.mp3"),
  "Right as rain": require("./assets/audio/Right as rain.mp3"),
  "Much obliged": require("./assets/audio/much obliged.mp3"),
  "The law": require("./assets/audio/The law.mp3"),
  "Bounty": require("./assets/audio/Bounty.mp3"),
  "Outlaw": require("./assets/audio/Out law.mp3"),
  "Hold up": require("./assets/audio/Hold up.mp3"),
  "Shootout": require("./assets/audio/Shoot out.mp3"),
  "Yellow-belly": require("./assets/audio/Yellow-belly.mp3"),
  "Make a run for it": require("./assets/audio/Make a run for it.mp3"),
  "Camp": require("./assets/audio/camp.mp3"),
  "Grub": require("./assets/audio/Grub.mp3"),
  "Saloon": require("./assets/audio/Saloon.mp3"),
  "Stable": require("./assets/audio/stable.mp3"),
  "Homestead": require("./assets/audio/Homestead.mp3"),
  "Trading post": require("./assets/audio/Trading post.mp3"),
  "Pelt": require("./assets/audio/pelt.mp3"),
  "Trapper": require("./assets/audio/trapper.mp3"),
  "High noon": require("./assets/audio/high noon.mp3"),
  "On the run": require("./assets/audio/on the run.mp3"),
  "Rustling cattle": require("./assets/audio/Rustling cattle.mp3"),
  "Wanted poster": require("./assets/audio/wanted poster.mp3"),
  "Hit the trail": require("./assets/audio/hit the trail.mp3"),
  "Hang him high": require("./assets/audio/hang him high.mp3"),
  "Shoot the breeze": require("./assets/audio/shoot the breeze.mp3"),
  "Easy there": require("./assets/audio/easy there.mp3"),
  "Son of a gun": require("./assets/audio/son of a gun.mp3"),
  "Blood on your hands": require("./assets/audio/blood on your hands.mp3"),
  "Ride out": require("./assets/audio/ride out.mp3"),
  "Lay low": require("./assets/audio/lay low.mp3"),
  "By the fire": require("./assets/audio/by the fire.mp3"),
  "Go fetch": require("./assets/audio/go fetch.mp3"),
  "Marshal": require("./assets/audio/Marshal.mp3"),
  "Sheriff": require("./assets/audio/sheriff.mp3"),
  "Deputy": require("./assets/audio/deputy.mp3"),
  "Posse": require("./assets/audio/posse.mp3"),
  "Holster": require("./assets/audio/holster.mp3"),
  "Break a horse": require("./assets/audio/break a horse.mp3"),
  "General store": require("./assets/audio/general store.mp3"),
  "Wanted level": require("./assets/audio/wanted level.mp3"),
  "Witness": require("./assets/audio/witness.mp3"),
  "Report the crime": require("./assets/audio/report the crime.mp3"),
  "Stagecoach": require("./assets/audio/Stagecoach.mp3"),
  "Train job": require("./assets/audio/train job.mp3"),
  "Hideout": require("./assets/audio/hideout.mp3"),
  "Shakedown": require("./assets/audio/shake down.mp3"),
  "Take cover": require("./assets/audio/take cover.mp3"),
  "Peacemaker": require("./assets/audio/peacemaker.mp3"),
  "Holdup note": require("./assets/audio/holdup note.mp3"),
  "Wanted dead": require("./assets/audio/Wanted dead.mp3"),
  "Wanted alive": require("./assets/audio/wanted alive.mp3"),
  "Camp chores": require("./assets/audio/camp chores.mp3"),
  "Ledger": require("./assets/audio/ledger.mp3"),
  "Tonic": require("./assets/audio/tonic.mp3"),
  "Provision": require("./assets/audio/provision.mp3"),
  "Satchel": require("./assets/audio/satchel.mp3"),
  "Bounty hunter": require("./assets/audio/bounty hunter.mp3"),
  "Wanted witness": require("./assets/audio/wanted witness.mp3"),
  "Antagonize": require("./assets/audio/antagonize.mp3"),
  "Honor": require("./assets/audio/honor.mp3"),
  "Camp contribution": require("./assets/audio/camp contribution.mp3"),
  "Fence wagon": require("./assets/audio/fence wagon.mp3"),
  "Fence buyer": require("./assets/audio/fence buyer.mp3"),
};